/*
 * Procurify API Documentation
 *  # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.APCreditCard;
import com.konfigthis.client.model.ExpenseDocs;
import com.konfigthis.client.model.PurchaseOrderRead;
import com.konfigthis.client.model.StatementItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreditCardItemRead
 */
public class CreditCardItemReadTest {
    private final CreditCardItemRead model = new CreditCardItemRead();

    /**
     * Model tests for CreditCardItemRead
     */
    @Test
    public void testCreditCardItemRead() {
        // TODO: test CreditCardItemRead
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'creditcard'
     */
    @Test
    public void creditcardTest() {
        // TODO: test creditcard
    }

    /**
     * Test the property 'po'
     */
    @Test
    public void poTest() {
        // TODO: test po
    }

    /**
     * Test the property 'expense'
     */
    @Test
    public void expenseTest() {
        // TODO: test expense
    }

    /**
     * Test the property 'creditcardIsEditable'
     */
    @Test
    public void creditcardIsEditableTest() {
        // TODO: test creditcardIsEditable
    }

    /**
     * Test the property 'matchedStatementItems'
     */
    @Test
    public void matchedStatementItemsTest() {
        // TODO: test matchedStatementItems
    }

}
