/*
 * Procurify API Documentation
 *  # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ApprovalDelegationReadNullable;
import com.konfigthis.client.model.UserSummary;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MasterLogger
 */
public class MasterLoggerTest {
    private final MasterLogger model = new MasterLogger();

    /**
     * Model tests for MasterLogger
     */
    @Test
    public void testMasterLogger() {
        // TODO: test MasterLogger
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'nextApprover'
     */
    @Test
    public void nextApproverTest() {
        // TODO: test nextApprover
    }

    /**
     * Test the property 'nextApprover'
     */
    @Test
    public void nextApproverTest() {
        // TODO: test nextApprover
    }

    /**
     * Test the property 'approvalDelegation'
     */
    @Test
    public void approvalDelegationTest() {
        // TODO: test approvalDelegation
    }

    /**
     * Test the property 'dateTime'
     */
    @Test
    public void dateTimeTest() {
        // TODO: test dateTime
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'lineQtyPass'
     */
    @Test
    public void lineQtyPassTest() {
        // TODO: test lineQtyPass
    }

    /**
     * Test the property 'lineQtyFail'
     */
    @Test
    public void lineQtyFailTest() {
        // TODO: test lineQtyFail
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

    /**
     * Test the property 'lineItem'
     */
    @Test
    public void lineItemTest() {
        // TODO: test lineItem
    }

    /**
     * Test the property 'PO'
     */
    @Test
    public void POTest() {
        // TODO: test PO
    }

    /**
     * Test the property 'inventoryItem'
     */
    @Test
    public void inventoryItemTest() {
        // TODO: test inventoryItem
    }

    /**
     * Test the property 'stockingParent'
     */
    @Test
    public void stockingParentTest() {
        // TODO: test stockingParent
    }

}
