/*
 * Procurify API Documentation
 *  # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AddressSummary;
import com.konfigthis.client.model.CostDetailsNullable;
import com.konfigthis.client.model.CreditCardReadNullable;
import com.konfigthis.client.model.CurrencySummary;
import com.konfigthis.client.model.CustomFieldValueRead;
import com.konfigthis.client.model.ExpenseTypeEnumNullable;
import com.konfigthis.client.model.FulfilmentStatusEnum;
import com.konfigthis.client.model.PaymentTerm;
import com.konfigthis.client.model.PriceModifierDocs;
import com.konfigthis.client.model.PurchaseOrderContract;
import com.konfigthis.client.model.PurchaseOrderLineItemRead;
import com.konfigthis.client.model.ShippingMethod;
import com.konfigthis.client.model.ShippingTerm;
import com.konfigthis.client.model.UserSummary;
import com.konfigthis.client.model.VendorRead;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PurchaseOrderDetail
 */
public class PurchaseOrderDetailTest {
    private final PurchaseOrderDetail model = new PurchaseOrderDetail();

    /**
     * Model tests for PurchaseOrderDetail
     */
    @Test
    public void testPurchaseOrderDetail() {
        // TODO: test PurchaseOrderDetail
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'purchaser'
     */
    @Test
    public void purchaserTest() {
        // TODO: test purchaser
    }

    /**
     * Test the property 'procurifyPO'
     */
    @Test
    public void procurifyPOTest() {
        // TODO: test procurifyPO
    }

    /**
     * Test the property 'poNum'
     */
    @Test
    public void poNumTest() {
        // TODO: test poNum
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'buyerName'
     */
    @Test
    public void buyerNameTest() {
        // TODO: test buyerName
    }

    /**
     * Test the property 'buyerContact'
     */
    @Test
    public void buyerContactTest() {
        // TODO: test buyerContact
    }

    /**
     * Test the property 'buyerAddressLineOne'
     */
    @Test
    public void buyerAddressLineOneTest() {
        // TODO: test buyerAddressLineOne
    }

    /**
     * Test the property 'buyerPostalCode'
     */
    @Test
    public void buyerPostalCodeTest() {
        // TODO: test buyerPostalCode
    }

    /**
     * Test the property 'buyerCity'
     */
    @Test
    public void buyerCityTest() {
        // TODO: test buyerCity
    }

    /**
     * Test the property 'buyerStateProvince'
     */
    @Test
    public void buyerStateProvinceTest() {
        // TODO: test buyerStateProvince
    }

    /**
     * Test the property 'buyerCountry'
     */
    @Test
    public void buyerCountryTest() {
        // TODO: test buyerCountry
    }

    /**
     * Test the property 'buyerAddress'
     */
    @Test
    public void buyerAddressTest() {
        // TODO: test buyerAddress
    }

    /**
     * Test the property 'receiverName'
     */
    @Test
    public void receiverNameTest() {
        // TODO: test receiverName
    }

    /**
     * Test the property 'receiverContact'
     */
    @Test
    public void receiverContactTest() {
        // TODO: test receiverContact
    }

    /**
     * Test the property 'receiverAddressLineOne'
     */
    @Test
    public void receiverAddressLineOneTest() {
        // TODO: test receiverAddressLineOne
    }

    /**
     * Test the property 'receiverPostalCode'
     */
    @Test
    public void receiverPostalCodeTest() {
        // TODO: test receiverPostalCode
    }

    /**
     * Test the property 'receiverCity'
     */
    @Test
    public void receiverCityTest() {
        // TODO: test receiverCity
    }

    /**
     * Test the property 'receiverStateProvince'
     */
    @Test
    public void receiverStateProvinceTest() {
        // TODO: test receiverStateProvince
    }

    /**
     * Test the property 'receiverCountry'
     */
    @Test
    public void receiverCountryTest() {
        // TODO: test receiverCountry
    }

    /**
     * Test the property 'receiverAddress'
     */
    @Test
    public void receiverAddressTest() {
        // TODO: test receiverAddress
    }

    /**
     * Test the property 'prefVendor'
     */
    @Test
    public void prefVendorTest() {
        // TODO: test prefVendor
    }

    /**
     * Test the property 'vendorName'
     */
    @Test
    public void vendorNameTest() {
        // TODO: test vendorName
    }

    /**
     * Test the property 'vendorContact'
     */
    @Test
    public void vendorContactTest() {
        // TODO: test vendorContact
    }

    /**
     * Test the property 'vendorAddressLineOne'
     */
    @Test
    public void vendorAddressLineOneTest() {
        // TODO: test vendorAddressLineOne
    }

    /**
     * Test the property 'vendorPostalCode'
     */
    @Test
    public void vendorPostalCodeTest() {
        // TODO: test vendorPostalCode
    }

    /**
     * Test the property 'vendorCity'
     */
    @Test
    public void vendorCityTest() {
        // TODO: test vendorCity
    }

    /**
     * Test the property 'vendorStateProvince'
     */
    @Test
    public void vendorStateProvinceTest() {
        // TODO: test vendorStateProvince
    }

    /**
     * Test the property 'vendorCountry'
     */
    @Test
    public void vendorCountryTest() {
        // TODO: test vendorCountry
    }

    /**
     * Test the property 'paymentTerms'
     */
    @Test
    public void paymentTermsTest() {
        // TODO: test paymentTerms
    }

    /**
     * Test the property 'shippingTerms'
     */
    @Test
    public void shippingTermsTest() {
        // TODO: test shippingTerms
    }

    /**
     * Test the property 'shippingMethod'
     */
    @Test
    public void shippingMethodTest() {
        // TODO: test shippingMethod
    }

    /**
     * Test the property 'promiseDate'
     */
    @Test
    public void promiseDateTest() {
        // TODO: test promiseDate
    }

    /**
     * Test the property 'subtotal'
     */
    @Test
    public void subtotalTest() {
        // TODO: test subtotal
    }

    /**
     * Test the property 'freight'
     */
    @Test
    public void freightTest() {
        // TODO: test freight
    }

    /**
     * Test the property 'tax'
     */
    @Test
    public void taxTest() {
        // TODO: test tax
    }

    /**
     * Test the property 'discount'
     */
    @Test
    public void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'other'
     */
    @Test
    public void otherTest() {
        // TODO: test other
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'purchasedCurrency'
     */
    @Test
    public void purchasedCurrencyTest() {
        // TODO: test purchasedCurrency
    }

    /**
     * Test the property 'purchasedCurrencyRate'
     */
    @Test
    public void purchasedCurrencyRateTest() {
        // TODO: test purchasedCurrencyRate
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'fulfilmentStatus'
     */
    @Test
    public void fulfilmentStatusTest() {
        // TODO: test fulfilmentStatus
    }

    /**
     * Test the property 'disclaimerDescription'
     */
    @Test
    public void disclaimerDescriptionTest() {
        // TODO: test disclaimerDescription
    }

    /**
     * Test the property 'disclaimerText'
     */
    @Test
    public void disclaimerTextTest() {
        // TODO: test disclaimerText
    }

    /**
     * Test the property 'recordedDate'
     */
    @Test
    public void recordedDateTest() {
        // TODO: test recordedDate
    }

    /**
     * Test the property 'closedDate'
     */
    @Test
    public void closedDateTest() {
        // TODO: test closedDate
    }

    /**
     * Test the property 'lastModified'
     */
    @Test
    public void lastModifiedTest() {
        // TODO: test lastModified
    }

    /**
     * Test the property 'stagedForExport'
     */
    @Test
    public void stagedForExportTest() {
        // TODO: test stagedForExport
    }

    /**
     * Test the property 'itemCount'
     */
    @Test
    public void itemCountTest() {
        // TODO: test itemCount
    }

    /**
     * Test the property 'mostRecentVersion'
     */
    @Test
    public void mostRecentVersionTest() {
        // TODO: test mostRecentVersion
    }

    /**
     * Test the property 'punchoutSystem'
     */
    @Test
    public void punchoutSystemTest() {
        // TODO: test punchoutSystem
    }

    /**
     * Test the property 'purchaseAgreement'
     */
    @Test
    public void purchaseAgreementTest() {
        // TODO: test purchaseAgreement
    }

    /**
     * Test the property 'purchaseAgreementStatus'
     */
    @Test
    public void purchaseAgreementStatusTest() {
        // TODO: test purchaseAgreementStatus
    }

    /**
     * Test the property 'punchoutVendorReference'
     */
    @Test
    public void punchoutVendorReferenceTest() {
        // TODO: test punchoutVendorReference
    }

    /**
     * Test the property 'punchoutSupplierIcon'
     */
    @Test
    public void punchoutSupplierIconTest() {
        // TODO: test punchoutSupplierIcon
    }

    /**
     * Test the property 'punchoutSupplierName'
     */
    @Test
    public void punchoutSupplierNameTest() {
        // TODO: test punchoutSupplierName
    }

    /**
     * Test the property 'hasBlanketOrderItems'
     */
    @Test
    public void hasBlanketOrderItemsTest() {
        // TODO: test hasBlanketOrderItems
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

    /**
     * Test the property 'contract'
     */
    @Test
    public void contractTest() {
        // TODO: test contract
    }

    /**
     * Test the property 'orderItems'
     */
    @Test
    public void orderItemsTest() {
        // TODO: test orderItems
    }

    /**
     * Test the property 'creditcardIsEditable'
     */
    @Test
    public void creditcardIsEditableTest() {
        // TODO: test creditcardIsEditable
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'creditcard'
     */
    @Test
    public void creditcardTest() {
        // TODO: test creditcard
    }

    /**
     * Test the property 'paymentTerm'
     */
    @Test
    public void paymentTermTest() {
        // TODO: test paymentTerm
    }

    /**
     * Test the property 'shippingTerm'
     */
    @Test
    public void shippingTermTest() {
        // TODO: test shippingTerm
    }

    /**
     * Test the property 'costDetails'
     */
    @Test
    public void costDetailsTest() {
        // TODO: test costDetails
    }

}
