/*
 * Procurify API Documentation
 *  # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ZeroOneEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * RecurringOrderItemNullable
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class RecurringOrderItemNullable {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_START_DATE = "start_date";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private LocalDate startDate;

  public static final String SERIALIZED_NAME_FREQUENCY = "frequency";
  @SerializedName(SERIALIZED_NAME_FREQUENCY)
  private ZeroOneEnum frequency;

  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  private ZeroOneEnum duration;

  public static final String SERIALIZED_NAME_DURATION_QUANTITY = "duration_quantity";
  @SerializedName(SERIALIZED_NAME_DURATION_QUANTITY)
  private Long durationQuantity;

  public static final String SERIALIZED_NAME_RECURRING_PRICE = "recurring_price";
  @SerializedName(SERIALIZED_NAME_RECURRING_PRICE)
  private BigDecimal recurringPrice;

  public static final String SERIALIZED_NAME_PERIODS_COUNT = "periods_count";
  @SerializedName(SERIALIZED_NAME_PERIODS_COUNT)
  private Integer periodsCount;

  public RecurringOrderItemNullable() {
  }

  
  public RecurringOrderItemNullable(
     Integer id, 
     Integer periodsCount
  ) {
    this();
    this.id = id;
    this.periodsCount = periodsCount;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId() {
    return id;
  }




  public RecurringOrderItemNullable startDate(LocalDate startDate) {
    
    
    
    
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getStartDate() {
    return startDate;
  }


  public void setStartDate(LocalDate startDate) {
    
    
    
    this.startDate = startDate;
  }


  public RecurringOrderItemNullable frequency(ZeroOneEnum frequency) {
    
    
    
    
    this.frequency = frequency;
    return this;
  }

   /**
   * Get frequency
   * @return frequency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ZeroOneEnum getFrequency() {
    return frequency;
  }


  public void setFrequency(ZeroOneEnum frequency) {
    
    
    
    this.frequency = frequency;
  }


  public RecurringOrderItemNullable duration(ZeroOneEnum duration) {
    
    
    
    
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ZeroOneEnum getDuration() {
    return duration;
  }


  public void setDuration(ZeroOneEnum duration) {
    
    
    
    this.duration = duration;
  }


  public RecurringOrderItemNullable durationQuantity(Long durationQuantity) {
    if (durationQuantity != null && durationQuantity < 1) {
      throw new IllegalArgumentException("Invalid value for durationQuantity. Must be greater than or equal to 1.");
    }
    if (durationQuantity != null && durationQuantity > 4294967295) {
      throw new IllegalArgumentException("Invalid value for durationQuantity. Must be less than or equal to 4294967295.");
    }
    
    
    this.durationQuantity = durationQuantity;
    return this;
  }

   /**
   * Get durationQuantity
   * minimum: 1
   * maximum: 4294967295
   * @return durationQuantity
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Long getDurationQuantity() {
    return durationQuantity;
  }


  public void setDurationQuantity(Long durationQuantity) {
    if (durationQuantity != null && durationQuantity < 1) {
      throw new IllegalArgumentException("Invalid value for durationQuantity. Must be greater than or equal to 1.");
    }
    if (durationQuantity != null && durationQuantity > 4294967295) {
      throw new IllegalArgumentException("Invalid value for durationQuantity. Must be less than or equal to 4294967295.");
    }
    
    this.durationQuantity = durationQuantity;
  }


  public RecurringOrderItemNullable recurringPrice(BigDecimal recurringPrice) {
    
    
    
    
    this.recurringPrice = recurringPrice;
    return this;
  }

   /**
   * Get recurringPrice
   * @return recurringPrice
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getRecurringPrice() {
    return recurringPrice;
  }


  public void setRecurringPrice(BigDecimal recurringPrice) {
    
    
    
    this.recurringPrice = recurringPrice;
  }


   /**
   * Get periodsCount
   * @return periodsCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPeriodsCount() {
    return periodsCount;
  }



  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RecurringOrderItemNullable instance itself
   */
  public RecurringOrderItemNullable putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecurringOrderItemNullable recurringOrderItemNullable = (RecurringOrderItemNullable) o;
    return Objects.equals(this.id, recurringOrderItemNullable.id) &&
        Objects.equals(this.startDate, recurringOrderItemNullable.startDate) &&
        Objects.equals(this.frequency, recurringOrderItemNullable.frequency) &&
        Objects.equals(this.duration, recurringOrderItemNullable.duration) &&
        Objects.equals(this.durationQuantity, recurringOrderItemNullable.durationQuantity) &&
        Objects.equals(this.recurringPrice, recurringOrderItemNullable.recurringPrice) &&
        Objects.equals(this.periodsCount, recurringOrderItemNullable.periodsCount)&&
        Objects.equals(this.additionalProperties, recurringOrderItemNullable.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, startDate, frequency, duration, durationQuantity, recurringPrice, periodsCount, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecurringOrderItemNullable {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    durationQuantity: ").append(toIndentedString(durationQuantity)).append("\n");
    sb.append("    recurringPrice: ").append(toIndentedString(recurringPrice)).append("\n");
    sb.append("    periodsCount: ").append(toIndentedString(periodsCount)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("start_date");
    openapiFields.add("frequency");
    openapiFields.add("duration");
    openapiFields.add("duration_quantity");
    openapiFields.add("recurring_price");
    openapiFields.add("periods_count");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("frequency");
    openapiRequiredFields.add("duration");
    openapiRequiredFields.add("duration_quantity");
    openapiRequiredFields.add("recurring_price");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RecurringOrderItemNullable
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RecurringOrderItemNullable.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RecurringOrderItemNullable is not found in the empty JSON string", RecurringOrderItemNullable.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RecurringOrderItemNullable.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("recurring_price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `recurring_price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recurring_price").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RecurringOrderItemNullable.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RecurringOrderItemNullable' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RecurringOrderItemNullable> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RecurringOrderItemNullable.class));

       return (TypeAdapter<T>) new TypeAdapter<RecurringOrderItemNullable>() {
           @Override
           public void write(JsonWriter out, RecurringOrderItemNullable value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RecurringOrderItemNullable read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             RecurringOrderItemNullable instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RecurringOrderItemNullable given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RecurringOrderItemNullable
  * @throws IOException if the JSON string is invalid with respect to RecurringOrderItemNullable
  */
  public static RecurringOrderItemNullable fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RecurringOrderItemNullable.class);
  }

 /**
  * Convert an instance of RecurringOrderItemNullable to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

