/*
 * Procurify API Documentation
 *  # Disclaimer  - Procurify’s API is evolving and is subject to change at any time. Additionally, aspects of the API are undocumented, including certain methods, events, and properties. Given that both documented and undocumented aspects of the Procurify API may change at any time, the client relies on the API at their own risk. - Client (and/or client’s representative) is responsible for building, testing, and maintaining any API connection between Procurify and any other tool.  Procurify’s responsibility strictly involves providing support on clarifications in regards to the issued API document. - Procurify’s API is offered on an “as is” and “as available” basis, without warranties of any kind. By accepting this agreement, you agree that you have read the current API documentation, and accept the API functionality in its current state including current limitations. For questions and clarification around the documentation, please contact support@procurify.com. - In accordance with Section 2.(b) of our Subscription Services Agreement, Procurify reserves the right to deny access to our API at any time. If your API requests are too large and time out, contact us immediately to avoid possible suspension of access. - You may not attempt to reverse engineer or otherwise derive source code, trade secrets, or know-how in the Procurify API or portion thereof. You may not use the Procurify API to replicate or compete with core products or services offered by Procurify. 
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AddressRequest;
import com.konfigthis.client.model.LanguageEnum;
import com.konfigthis.client.model.LocationCreateUpsertRequest;
import com.konfigthis.client.model.LocationViewSerializerSingleCreate;
import com.konfigthis.client.model.LocationViewSerializerSingleRetrieve;
import com.konfigthis.client.model.PaginatedLocationViewSerializerListList;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LocationsApi
 */
@Disabled
public class LocationsApiTest {

    private static LocationsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new LocationsApi(apiClient);
    }

    /**
     * Create New Location
     *
     * Create New Location. Note: only users with superuser permission can create locations.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        String name = null;
        String currency = null;
        String phoneOne = null;
        AddressRequest primaryBillingAddress = null;
        AddressRequest primaryShippingAddress = null;
        List<AddressRequest> shippingAddresses = null;
        String url = null;
        String logo = null;
        String fax = null;
        String email = null;
        LanguageEnum language = null;
        Object locationTimezone = null;
        Boolean active = null;
        String externalId = null;
        String format = null;
        LocationViewSerializerSingleCreate response = api.create(name, currency, phoneOne, primaryBillingAddress, primaryShippingAddress, shippingAddresses)
                .url(url)
                .logo(logo)
                .fax(fax)
                .email(email)
                .language(language)
                .locationTimezone(locationTimezone)
                .active(active)
                .externalId(externalId)
                .format(format)
                .execute();
        // TODO: test validations
    }

    /**
     * Get Locations
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        Boolean active = null;
        String format = null;
        Boolean headquarter = null;
        String orderBy = null;
        Integer page = null;
        Integer pageSize = null;
        String search = null;
        PaginatedLocationViewSerializerListList response = api.list()
                .active(active)
                .format(format)
                .headquarter(headquarter)
                .orderBy(orderBy)
                .page(page)
                .pageSize(pageSize)
                .search(search)
                .execute();
        // TODO: test validations
    }

    /**
     * Get Location by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void retrieveTest() throws ApiException {
        String id = null;
        String format = null;
        LocationViewSerializerSingleRetrieve response = api.retrieve(id)
                .format(format)
                .execute();
        // TODO: test validations
    }

}
